
export const CREATE_MENU_ITEM_REQUEST = "CREATE_MENU_ITEM_REQUEST";
export const CREATE_MENU_ITEM_SUCCSESS = "CREATE_MENU_ITEM_SUCCSESS";
export const CREATE_MENU_ITEM_FAILURE = "CREATE_MENU_ITEM_FAILURE";

export const GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_REQUEST = "GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_REQUEST";
export const GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_SUCCSESS = "GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_SUCCSESS";
export const GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_FAILURE = "GET_ALL_MENUE_ITEMS_BY_RESTUARANTID_FAILURE";

export const GET_MENUE_ITEMS_BY_RESTUARANTID_REQUEST = "GET_MENUE_ITEMS_BY_RESTUARANTID_REQUEST";
export const GET_MENUE_ITEMS_BY_RESTUARANTID_SUCCSESS = "GET_MENUE_ITEMS_BY_RESTUARANTID_SUCCSESS";
export const GET_MENUE_ITEMS_BY_RESTUARANTID_FAILURE = "GET_MENUE_ITEMS_BY_RESTUARANTID_FAILURE";

export const DELETE_MENUE_ITEM_REQUEST = "DELETE_MENUE_ITEM_REQUEST";
export const DELETE_MENUE_ITEM_SUCCSESS = "DELETE_MENUE_ITEM_SUCCSESS";
export const DELETE_MENUE_ITEM_FAILURE = "DELETE_MENUE_ITEM_FAILURE";

export const SEARCH_MENU_ITEM_REQUEST = "SEARCH_MENU_ITEM_REQUEST";
export const SEARCH_MENU_ITEM_SUCCSESS = "SEARCH_MENU_ITEM_SUCCSESS";
export const SEARCH_MENU_ITEM_FAILURE = "SEARCH_MENU_ITEM_FAILURE";

export const UPDATE_MENUE_ITEMS_AVAILABILITY_REQUEST = "UPDATE_MENUE_ITEMS_AVAILABILITY_REQUEST";
export const UPDATE_MENUE_ITEMS_AVAILABILITY_SUCCSESS = "UPDATE_MENUE_ITEMS_AVAILABILITY_SUCCSESS";
export const UPDATE_MENUE_ITEMS_AVAILABILITY_FAILURE = "UPDATE_MENUE_ITEMS_AVAILABILITY_FAILURE";